services:
  dev:
    restart: no
    networks:
      - jan1tor
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:debug

  prod:
    restart: on-failure:3
    networks:
      - jan1tor
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ./app/data:/app/dist/data
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start

networks:
  jan1tor:
    driver: bridge


